name: unbound
favicon: null
layout_spectrum: 0.7547710393555462
typography_spectrum: 0.008821337716653943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.37064800993539393
  lightness: 0.6338480419944972
  saturation: 0.1673581909853965
  rhythmicContrast: 0.03793141269125044
purpose: []
