typography_spectrum: 0.008821337716653943
color:
  brandColors:
    - '#020703'
    - '#fefefe'
    - '#cec9de'
    - '#d16f48'
    - '#9790b5'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74308
analytics:
  google: null
  facebook: null
  twitter: null
name: unbound
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: unbound
description: stuff I like
purpose: []
